# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 027f58c91260242295e075e6b463fe96f12f7a621d4b85ce7f1a81514393c868afe9f77742e94b4331ea94e3f88a24a44ec0e11432debc5b1733010058399996

test:
  secret_key_base: b80ad4a7d49928e021fe5d1df9bb2aab501b575f258629c29b3073e3d7db4aed709849204557f41a0b0295d717e5acc083d37cfec373251f8e0e574de8b984d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
